### ISSUE TITLE
Why does not follow PEP8?

### ISSUE THREAD

**Issue by mingrammer** [hunkim/translation_coverage#1]
Why does not follow PEP8?

Can I fix that?

**Comment by hunkim** [comment]
Please do. I am not familiar with PEP8. Thanks!

**Comment by mingrammer** [comment]
I'm fixing that now :)

**Comment by hunkim** [comment]
How did you do that? Are you using checkers or something? http://stackoverflow.com/questions/14328406

**Comment by mingrammer** [comment]
I did not use automatic tools like that.
But, I'm using PEP8 lint plugin in vim. This checks the PEP8 convention on save time. So, I fixed using this by hand because the files have small size.

When the files will be plentiful or large, I'll use automatic tools like that in your link.

**Comment by mingrammer** [comment]
Ah, sorry for missing some PEP8 conventions. I ignored the 'length of line < 80' one of PEP8 and applied the PEP8 loosely. (it is often ignored by some developers. but of course not really PEP8)

**Comment by mingrammer** [comment]
Thanks to fix them on #8
