### ISSUE TITLE
Test is failed

### ISSUE THREAD

**Issue by mingrammer** [hunkim/translation_coverage#2]
I've ran the uniitest on my machine. then it is failed.

It seems that korean letters are not filtered by 'isalpha' function.

**Comment by hunkim** [comment]
Are you using Python 3.x?

**Comment by mingrammer** [comment]
both are failed with same error. (26 line. 0 != 7)

**Comment by hunkim** [comment]
I'll look into it. 2.7 on travis look OK. 

https://travis-ci.org/hunkim/translation_coverage/jobs/166415426

**Comment by mingrammer** [comment]
Sorry for my mistake. I didn't know my other virtualenv setting is activated (Python 3.5) :| ..

Yes, it is ok in Python 2.x

**Comment by mingrammer** [comment]
So, I'll check #3

**Comment by hunkim** [comment]
I think isalpha works differently in Python 3.X.
