### ISSUE TITLE
Error on example (should be 0, but not)

### ISSUE THREAD

**Issue by hunkim** [hunkim/translation_coverage#22]
@mingrammer Could you check our examples?

https://github.com/tensorflowkorea/tensorflow-kr/blob/master/progress.md

For example, word2vec should be 0, but it's not the case.

**Comment by mingrammer** [comment]
There are some source code. I think these are conuted as non-english characters.

**Comment by mingrammer** [comment]
Do you want if some files does not have any korean (or other translated langauge) should have 0?

**Comment by hunkim** [comment]
I think we should show the progress of translation. It should be the rate between English and Non-English words. I think we should exclude source code and other taggings when we compute the rate.

**Comment by hunkim** [comment]
"should have 0?" Yes, so that people clearly know what they should work on. :-)

**Comment by hunkim** [comment]
``` python
    def test_trans_coverage_file_source_code(self):
        e_count, n_count = main.trans_coverage_file("tests/sample_source_code.md")
        print("sample_source_code: ", e_count, n_count)
        self.assertEqual(e_count, 0)
        self.assertNotEqual(n_count, 0)
```

I guess `self.assertNotEqual(n_count, 0)` should be `self.assertEqual(n_count, 0)`.

**Comment by mingrammer** [comment]
Yes. hmm.. so the source code (or others not normal text) should be ignored completely (does not counted at all)?

**Comment by mingrammer** [comment]
If there is complete source code, we may mark this as 0(%). right?

**Comment by hunkim** [comment]
Sure.

Sung

**Comment by mingrammer** [comment]
So, how about this?
1. If some files are complete source code, we mark this as like 'This is source code' and make it's percentage to 100(%)
2. If some files have source code partially, we should mark it as 0(%) if there are no any translation. But, if translation for that files are almost completed, we also could count the source code at this time. (In this case, we should choose appropriate value)

Is it complex? or any ideas?

**Comment by hunkim** [comment]
Let's keep it simple. Just exclude source code in the equation.

**Comment by mingrammer** [comment]
Ok, I'll just exclude source code not counting length of that.
