### ISSUE TITLE
[Proposal] Support colored text

### ISSUE THREAD

**Issue by mingrammer** [hunkim/translation_coverage#24]
We are marking the text according to value of coverage as **bold** or _italic_.
The idea is good, but, it is not distinguish well.

So, I suggest that we should mark these as colored text. For example, If coverage is greater than 50(%), we could clothe specific color to the text. (e.g., dark-green)

I want to listen your thought.

**Comment by hunkim** [comment]
Wonderful idea!

**Comment by mingrammer** [comment]
@hunkim Assign to me :D

**Comment by mingrammer** [comment]
Oh, there is a problem. Github does not support custom html tags. So we can't make colored text :(

So .. we should find alternative like .. this

[![](https://img.shields.io/badge/coverage-86-brightgreen.svg)]()

However, because it needs http call, so sometimes has big overhead. 

Any ideas to distinguish well?

**Comment by hunkim** [comment]
Can you use emoticons?

**Comment by mingrammer** [comment]
Wow, that's great idea! 👍 

like this? (it's just example)
🌑
🌓
🌔

Of course, I should pick some appropriate emoji :D

**Comment by hunkim** [comment]
Wonderful!

**Comment by hunkim** [comment]
Looks very good!

**Comment by hunkim** [comment]
We can add some emoticons, right? Could we use them?
